var GAME_LEVELS = [
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x!                                                                              x",
   "x           y           y y                                                    x",
   "x   @      xxx         xxxxx                                                   x",
   "x  xxx                                     y  y  y  y  y  y  y                 x",
   "xxxxxxxx          xx                                                          !x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx          x",
   "x                                                                              x",
   "x                                                                              x",
   "x                                                                              x",
   "x            y y y y y y y y y y y y y y                                       x",
   "x           y y y y y y y y y y y y y y y                                   y yx",
   "x                                                                              x",
   "xx      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                 xxxx",
   "x                       x | x | x| |      xxxx                                 x",
   "x    y                                    xxx            y  y                  x",
   "x    y                                                                         x",
   "x    y                                                 xxxxxxxx                x",
   "x                                                     x        x               x",
   "x            x         y  y  y  y                    x    s     x              x",
   "x            xx                                       xxx    xxx               x",
   "x    o       xxx                                                               x",
   "x            xxxx       x| |x| |x | x                                           x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["                                                                                                             xxx  ",
   "                                                                                                             xxx  ",
   "                                                                                                             xxx  ",
   "                                                                                                             xxx  ",
   "                        y                     y                 y             yy                y  y  y  y   xxx  ",
   " @                                                                                               yy yy yy    xxx  ",
   "xxxxxxxx               xxx                   xxx               xxx           xxxx             xxxxxxxxxxxxxxxxxx  ",
   "!             x         !          x          !        x        !      x       !        x                    !xx  ",
   "xxxxxXxx               xxx                   xxx               xxx           xxxx             xxxxxxxxxxxxxxxxxx  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                               x     x                           xxx         xxx                  ",
   "                                               x     x                           x x         x x                  ",
   "                                               xy    x                             x         x                    ",
   "                                               xy    x                             xx        x                    ",
   "                 y  t                          xx    x                             x         x                    ",
   "                                               x     x         y     x   x         x y       x                    ",
   "               xxxxxxx                         x    yx               x   x         x y       x                    ",
   "              xx     xx                        x    yx        xxx    x   x   xxxxxxxxx       x                    ",
   "             xx       xx                       x    xx     y         x   x   x               x                    ",
   "             x         xxxxxxxxxxxxxxxxxx      x  s  x               x   x   x               x                    ",
   "                                                          xxx                                                     ",
   "                                           y        o        y                                                    ",
   "                                                                                                                  ",
   "                                x         xxxxxxxxxxxxxxxxxxxxx          x                                        ",
   "                            r xxx  r   xxxx                   xxxxx   r  xxx r                                    ",
   "      y y y                 xxxxxxxx                                  xxxxxxx                y y y               ",
   "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x           |                                               |                                                x",
   "x                                                                                                            x",
   "x         |   |                                               |                                              x",
   "x                                                                                                            x",
   "x @     |       |                                               |                                            x",
   "x                                                                                                            x",
   "x    y|y y y y y y|y          y  y  y                      r y y y|y y|y     y  y  y                     o   x",
   "x                                                                                                            x",
   "x   |              xwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwx        |  xwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]
  
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
